Reuse zmalloc mechanism for increment/decrement size
memKeyDB/memKeyDB pull request #33
Opened 2020-07-10 13:05 UTC by michalbiesek

Ref #23

2020-07-10 13:31 UTC, jschmieg approved these changes

2020-07-10 15:20 UTC, kasiawasiuta requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/33)* status: all files reviewed, 5 unresolved discussions (waiting on @michalbiesek)

___
*[src/atomicvar.h, line 19 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/33#-MBtFevFCsX3nM3FxGzm:-MBtFevFCsX3nM3FxGzn:b-fhjtfb) ([raw file](https://github.com/memkeydb/memkeydb/blob/d5ab4ef93f619e96886fc06e23f25a3f6e9a5832/src/atomicvar.h#L19)):*
> ```
> (tested in config.h) the mutex
> ```
(tested in config.h), the mutex
___
*[src/atomicvar.h, line 25 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/33#-MBtFqzO6pMY7J41PFec:-MBtFqzO6pMY7J41PFed:b-xt1xg2) ([raw file](https://github.com/memkeydb/memkeydb/blob/d5ab4ef93f619e96886fc06e23f25a3f6e9a5832/src/atomicvar.h#L25)):*
> ```
> followign
> ```
typo
___
*[src/zmalloc.c, line 503 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/33#-MBtHeQgCHV1JxDauqWI:-MBtHeQh8gH90sqrJkWa:bf0wukl) ([raw file](https://github.com/memkeydb/memkeydb/blob/d5ab4ef93f619e96886fc06e23f25a3f6e9a5832/src/zmalloc.c#L503)):*
> ```
> where there is a "LIST_HEAD" macro (!) defined
> ```
where a "LIST_HEAD" macro (!) is defined,
___
*[src/zmalloc.c, line 512 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/33#-MBtHzSGDXRoCxHd6Wos:-MBtHzSGDXRoCxHd6Wot:bhfesoa) ([raw file](https://github.com/memkeydb/memkeydb/blob/d5ab4ef93f619e96886fc06e23f25a3f6e9a5832/src/zmalloc.c#L512)):*
> ```
> such a pid,
> ```
such pid,
___
*[src/zmalloc.c, line 514 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/33#-MBtI9ui1iHybeSaNssg:-MBtI9ui1iHybeSaNssh:btmvth5) ([raw file](https://github.com/memkeydb/memkeydb/blob/d5ab4ef93f619e96886fc06e23f25a3f6e9a5832/src/zmalloc.c#L514)):*
> ```
>  * otherwise if pid is -1 the information is reported is about the
>  * current process.
> ```
otherwise if pid is -1, the information is reported about the current process.


<!-- Sent from Reviewable.io -->

2020-07-10 15:29 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/33)* status: all files reviewed, 5 unresolved discussions (waiting on @kasiawasiuta)

___
*[src/atomicvar.h, line 19 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/33#-MBtFevFCsX3nM3FxGzm:-MBtK9UJBqnpgnoChERR:b-xoglof) ([raw file](https://github.com/memkeydb/memkeydb/blob/d5ab4ef93f619e96886fc06e23f25a3f6e9a5832/src/atomicvar.h#L19)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

> ```
> (tested in config.h) the mutex
> ```
(tested in config.h), the mutex
</blockquote></details>

Copied from https://github.com/memKeyDB/memKeyDB/blob/8356e33f5c81452caa0c6fdce09a66d1116b4862/src/atomicvar.h#L19 I will not fix it now unless it will be fixed in origin place in this case 6.0 branch - see my git commit message
___
*[src/atomicvar.h, line 25 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/33#-MBtFqzO6pMY7J41PFec:-MBtKNa9AfDWxW3v2Dvp:b-tfw2s3) ([raw file](https://github.com/memkeydb/memkeydb/blob/d5ab4ef93f619e96886fc06e23f25a3f6e9a5832/src/atomicvar.h#L25)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

> ```
> followign
> ```
typo
</blockquote></details>

Copied from:
https://github.com/memKeyDB/memKeyDB/blob/8356e33f5c81452caa0c6fdce09a66d1116b4862/src/atomicvar.h#L24 I will not fix it now unless it will be fixed in origin place in this case 6.0 branch - see my git commit message
___
*[src/zmalloc.c, line 503 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/33#-MBtHeQgCHV1JxDauqWI:-MBtKWMG953vlAClAdRr:br71jr4) ([raw file](https://github.com/memkeydb/memkeydb/blob/d5ab4ef93f619e96886fc06e23f25a3f6e9a5832/src/zmalloc.c#L503)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

> ```
> where there is a "LIST_HEAD" macro (!) defined
> ```
where a "LIST_HEAD" macro (!) is defined,
</blockquote></details>

Copied from:
https://github.com/memKeyDB/memKeyDB/blob/8356e33f5c81452caa0c6fdce09a66d1116b4862/src/zmalloc.c#L604 I will not fix it now unless it will be fixed in origin place in this case 6.0 branch - see my git commit message
___
*[src/zmalloc.c, line 512 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/33#-MBtHzSGDXRoCxHd6Wos:-MBtKeVd97ksvxieuR_o:b8hsue6) ([raw file](https://github.com/memkeydb/memkeydb/blob/d5ab4ef93f619e96886fc06e23f25a3f6e9a5832/src/zmalloc.c#L512)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

> ```
> such a pid,
> ```
such pid,
</blockquote></details>

Copied from:
https://github.com/memKeyDB/memKeyDB/blob/8356e33f5c81452caa0c6fdce09a66d1116b4862/src/zmalloc.c#L613 I will not fix it now unless it will be fixed in origin place in this case 6.0 branch - see my git commit message
___
*[src/zmalloc.c, line 514 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/33#-MBtI9ui1iHybeSaNssg:-MBtL3eABJB-BiNRvgob:b-b2jbs1) ([raw file](https://github.com/memkeydb/memkeydb/blob/d5ab4ef93f619e96886fc06e23f25a3f6e9a5832/src/zmalloc.c#L514)):*
<details><summary><i>Previously, kasiawasiuta wrote…</i></summary><blockquote>

> ```
>  * otherwise if pid is -1 the information is reported is about the
>  * current process.
> ```
otherwise if pid is -1, the information is reported about the current process.
</blockquote></details>

Copied from:
https://github.com/memKeyDB/memKeyDB/blob/8356e33f5c81452caa0c6fdce09a66d1116b4862/src/zmalloc.c#L614 I will not fix it now unless it will be fixed in origin place in this case 6.0 branch - see my git commit message


<!-- Sent from Reviewable.io -->

2020-07-13 07:44 UTC, kasiawasiuta approved these changes
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/33)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-07-13 09:05 UTC, merged