Travis configuration
memKeyDB/memKeyDB pull request #5
Opened 2020-03-23 07:35 UTC by kasiawasiuta

-Running unit tests for jemalloc and memkind allocators
-Generating coverage for memkind allocator

2020-03-23 21:04 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/5)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jschmieg, @kasiawasiuta, and @michalbiesek)

___
*[.travis.yml, line 2 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/5#-M382KiW-nr6sFoEuL4o:-M382KiW-nr6sFoEuL4p:b-44pagn) ([raw file](https://github.com/memkeydb/memkeydb/blob/805c44a22904da9a7165baa561a3fb52f7f672c2/.travis.yml#L2)):*
> ```
> sudo: false
> ```
nit: AFAIK this is not needed: https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments
___
*[.travis.yml, line 10 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/5#-M38AUh76bk_R5cN3_2_:-M38AUh76bk_R5cN3_2a:b-248o56) ([raw file](https://github.com/memkeydb/memkeydb/blob/805c44a22904da9a7165baa561a3fb52f7f672c2/.travis.yml#L10)):*
> ```
> - CONF="MALLOC=memkind"
> ```
As we spoke offline - IMHO this line should be introduced with integration of memkind allocator
___
*[.travis.yml, line 19 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/5#-M38AN5Z30BNBIZ-eF84:-M38AN5Z30BNBIZ-eF85:betelrw) ([raw file](https://github.com/memkeydb/memkeydb/blob/805c44a22904da9a7165baa561a3fb52f7f672c2/.travis.yml#L19)):*
> ```
> make test
> ```
This should fix failing test, instead of make test please call:
./runtest --clients 2


<!-- Sent from Reviewable.io -->

2020-03-24 10:20 UTC, kasiawasiuta reviewed
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/5)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @jschmieg and @michalbiesek)

___
*[.travis.yml, line 10 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/5#-M38AUh76bk_R5cN3_2_:-M3AzB75D5TZmEldnONF:b-896fix) ([raw file](https://github.com/memkeydb/memkeydb/blob/805c44a22904da9a7165baa561a3fb52f7f672c2/.travis.yml#L10)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> - CONF="MALLOC=memkind"
> ```
As we spoke offline - IMHO this line should be introduced with integration of memkind allocator
</blockquote></details>

Done.
___
*[.travis.yml, line 19 at r1](https://reviewable.io/reviews/memkeydb/memkeydb/5#-M38AN5Z30BNBIZ-eF84:-M3B-BZRBXxnCm6Z_aCv:b-896fix) ([raw file](https://github.com/memkeydb/memkeydb/blob/805c44a22904da9a7165baa561a3fb52f7f672c2/.travis.yml#L19)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> make test
> ```
This should fix failing test, instead of make test please call:
./runtest --clients 2
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-24 10:55 UTC, michalbiesek approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/memkeydb/memkeydb/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jschmieg)



<!-- Sent from Reviewable.io -->

2020-03-26 04:31 UTC, hongliuliao approved these changes

2020-04-17 13:36 UTC, merged